SELECT GB.TITLE AS TITLE, 
GB.BOARD_ID AS BOARD_ID, 
GR.REPLY_ID AS REPLY_ID, 
GR.WRITER_ID AS WRITER_ID, 
GR.CONTENTS AS CONTENTS, 
DATE_FORMAT(GR.CREATED_DATE ,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS GB JOIN USED_GOODS_REPLY AS GR ON GB.BOARD_ID = GR.BOARD_ID
WHERE GB.CREATED_DATE >= '2022-10-01' AND GB.CREATED_DATE <= '2022-10-31' 
ORDER BY GR.CREATED_DATE, GB.TITLE ASC;